// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamMatching.Web.Data;

#nullable disable

namespace TeamMatching.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526143608_tagtimetable")]
    partial class tagtimetable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TeamMatching.Shared.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentMembers")
                        .HasColumnType("int");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CommunicationScore")
                        .HasColumnType("float");

                    b.Property<float>("ContributionScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<float>("ReliabilityScore")
                        .HasColumnType("float");

                    b.Property<int>("RevieweeId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("PostId", "ReviewerId", "RevieweeId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C"
                        },
                        new
                        {
                            Id = 2,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 6,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 7,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Go"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rust"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 13,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 14,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 15,
                            Name = "R"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Dart"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Scala"
                        },
                        new
                        {
                            Id = 18,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Spring"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Spring Boot"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Express"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Django"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Flask"
                        },
                        new
                        {
                            Id = 25,
                            Name = "React"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Vue"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Svelte"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Next.js"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Nuxt.js"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 32,
                            Name = "React Native"
                        },
                        new
                        {
                            Id = 33,
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 34,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = 36,
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Redis"
                        },
                        new
                        {
                            Id = 38,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 39,
                            Name = "GCP"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Firebase"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 43,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 44,
                            Name = "프론트엔드"
                        },
                        new
                        {
                            Id = 45,
                            Name = "백엔드"
                        },
                        new
                        {
                            Id = 46,
                            Name = "모바일"
                        },
                        new
                        {
                            Id = 47,
                            Name = "기획"
                        },
                        new
                        {
                            Id = 48,
                            Name = "UI/UX"
                        },
                        new
                        {
                            Id = 49,
                            Name = "데이터분석"
                        },
                        new
                        {
                            Id = 50,
                            Name = "인공지능/AI"
                        },
                        new
                        {
                            Id = 51,
                            Name = "머신러닝"
                        },
                        new
                        {
                            Id = 52,
                            Name = "블록체인"
                        },
                        new
                        {
                            Id = 53,
                            Name = "보안/해킹"
                        },
                        new
                        {
                            Id = 54,
                            Name = "게임개발"
                        },
                        new
                        {
                            Id = 55,
                            Name = "알고리즘"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Unity"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Unreal"
                        },
                        new
                        {
                            Id = 58,
                            Name = "축구"
                        },
                        new
                        {
                            Id = 59,
                            Name = "농구"
                        },
                        new
                        {
                            Id = 60,
                            Name = "야구"
                        },
                        new
                        {
                            Id = 61,
                            Name = "배드민턴"
                        },
                        new
                        {
                            Id = 62,
                            Name = "테니스"
                        },
                        new
                        {
                            Id = 63,
                            Name = "탁구"
                        },
                        new
                        {
                            Id = 64,
                            Name = "볼링"
                        },
                        new
                        {
                            Id = 65,
                            Name = "골프"
                        },
                        new
                        {
                            Id = 66,
                            Name = "수영"
                        },
                        new
                        {
                            Id = 67,
                            Name = "자전거/라이딩"
                        },
                        new
                        {
                            Id = 68,
                            Name = "헬스/피트니스"
                        },
                        new
                        {
                            Id = 69,
                            Name = "크로스핏"
                        },
                        new
                        {
                            Id = 70,
                            Name = "요가/필라테스"
                        },
                        new
                        {
                            Id = 71,
                            Name = "러닝/마라톤"
                        },
                        new
                        {
                            Id = 72,
                            Name = "등산"
                        },
                        new
                        {
                            Id = 73,
                            Name = "캠핑"
                        },
                        new
                        {
                            Id = 74,
                            Name = "클라이밍"
                        },
                        new
                        {
                            Id = 75,
                            Name = "e스포츠"
                        },
                        new
                        {
                            Id = 76,
                            Name = "밴드"
                        },
                        new
                        {
                            Id = 77,
                            Name = "보컬"
                        },
                        new
                        {
                            Id = 78,
                            Name = "건반"
                        },
                        new
                        {
                            Id = 79,
                            Name = "기타(악기)"
                        },
                        new
                        {
                            Id = 80,
                            Name = "베이스"
                        },
                        new
                        {
                            Id = 81,
                            Name = "드럼"
                        },
                        new
                        {
                            Id = 82,
                            Name = "작곡/미디"
                        },
                        new
                        {
                            Id = 83,
                            Name = "클래식"
                        },
                        new
                        {
                            Id = 84,
                            Name = "독서"
                        },
                        new
                        {
                            Id = 85,
                            Name = "어학"
                        },
                        new
                        {
                            Id = 86,
                            Name = "사진/출사"
                        },
                        new
                        {
                            Id = 87,
                            Name = "영상제작"
                        },
                        new
                        {
                            Id = 88,
                            Name = "맛집탐방"
                        },
                        new
                        {
                            Id = 89,
                            Name = "보드게임"
                        },
                        new
                        {
                            Id = 90,
                            Name = "방탈출"
                        },
                        new
                        {
                            Id = 91,
                            Name = "영화/드라마"
                        },
                        new
                        {
                            Id = 92,
                            Name = "전시/공연"
                        },
                        new
                        {
                            Id = 93,
                            Name = "댄스"
                        },
                        new
                        {
                            Id = 94,
                            Name = "드로잉/그림"
                        },
                        new
                        {
                            Id = 95,
                            Name = "자격증"
                        },
                        new
                        {
                            Id = 96,
                            Name = "취업/면접"
                        },
                        new
                        {
                            Id = 97,
                            Name = "토익/토플"
                        },
                        new
                        {
                            Id = 98,
                            Name = "고시/공무원"
                        },
                        new
                        {
                            Id = 99,
                            Name = "창업/스타트업"
                        });
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlotStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamAvailabilities");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Position")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPosts");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamPostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TeamPostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamPostId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamPostComments");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<float>("CommunicationScore")
                        .HasColumnType("float");

                    b.Property<float>("ContributionScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("longtext");

                    b.Property<float>("ReliabilityScore")
                        .HasColumnType("float");

                    b.Property<string>("StudentId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.UserTag", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("UserTags");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Application", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.Post", "Post")
                        .WithMany("Applications")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.User", "User")
                        .WithMany("MyApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Post", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.User", "Author")
                        .WithMany("MyPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.PostTag", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Review", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.User", "Reviewee")
                        .WithMany("ReceivedReviews")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.User", "Reviewer")
                        .WithMany("WrittenReviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Team", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamAvailability", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.TeamMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamMember", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamPost", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.Team", "Team")
                        .WithMany("TeamPosts")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamPostComment", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.TeamPost", "TeamPost")
                        .WithMany("TeamPostComments")
                        .HasForeignKey("TeamPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.UserTag", b =>
                {
                    b.HasOne("TeamMatching.Shared.Entities.Tag", "Tag")
                        .WithMany("UserTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamMatching.Shared.Entities.User", "User")
                        .WithMany("UserTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Post", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Tag", b =>
                {
                    b.Navigation("PostTags");

                    b.Navigation("UserTags");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.Team", b =>
                {
                    b.Navigation("TeamMembers");

                    b.Navigation("TeamPosts");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.TeamPost", b =>
                {
                    b.Navigation("TeamPostComments");
                });

            modelBuilder.Entity("TeamMatching.Shared.Entities.User", b =>
                {
                    b.Navigation("MyApplications");

                    b.Navigation("MyPosts");

                    b.Navigation("ReceivedReviews");

                    b.Navigation("TeamMemberships");

                    b.Navigation("UserTags");

                    b.Navigation("WrittenReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
